import { Inter } from 'next/font/google';
import Script from 'next/script';

import { ConvexClientProvider } from '@/providers/convex-client-provider';
import { Toaster } from '@/components/ui/sonner';

import type { Metadata } from 'next';

import './globals.css';
import { ModalProvider } from '@/providers/modal-provider';
import { Suspense } from 'react';
import { Loading } from './board/[boardId]/_components/loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <ConvexClientProvider>
            <Toaster />
            <ModalProvider />
            {children}
          </ConvexClientProvider>
        </Suspense>
        <Script
          defer
          src="https://analytics.h1a1ah.com/script.js"
          data-website-id="51222aa2-619f-444b-a8ff-c68efaaedf06"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
